config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'our_purpose', to: 'purpose#index'
  get 'contact_us', to: 'contact#index'

  resources :products, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :pictures, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    product = Product.new(product_params)
    
    if product.save
      render json: {}, status: :ok
    else
      render json: {}, status: :bad_request
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, { pictures: [] })
  end
end

app/controllers/purpose_controller.rb
class PurposeController < ApplicationController
  def index; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @carpincho = Product.find_by(name: 'Carpincho')
    @coati = Product.find_by(name: 'Coati')
    @tamandua = Product.find_by(name: 'Tamandua')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.haml
= render 'shared/top_background.html.haml', title: t('contact_us')

.full-height-wrapper.d-flex.flex-column.justify-content-center
  #contact-us.row.no-gutters.align-items-center
    .contact-form.col-12.col-lg-8.mb-5.row.no-gutters.justify-content-center
      %form.col-lg-6
        .form-group
          %input.form-control{placeholder: t('name'), name: 'name', type: 'text'}
        .form-group
          %input.form-control{placeholder: t('email'), name: 'email', type: 'email'}
        .form-group
          %input.form-control{placeholder: t('phone'), name: 'phone'}
        .form-group
          %textarea.form-control{placeholder: t('write_message'), name: 'message'}
          .row.no-gutters.justify-content-center
            %button.col-8.btn.btn-secondary.btn-lg.rounded.mt-5
              = t('send')

    .contact-information.col-12.col-lg-4.row.no-gutters.justify-content-around.align-items-center
      .whatsapp.col-12.col-md-4.col-lg-12.row.no-gutters.justify-content-center.mb-5
        .row.no-gutters.justify-content-center.align-items-center.col-12
          %h4.text-tertiary.mx-2 Charlá con nosotros
        .row.no-gutters.justify-content-start.align-items-center.mb-3.mx-4
          = image_pack_tag 'social_links/whatsapp.png', class: 'mr-3'
          %h5.text-tertiary.m-0 09X XXX XXX
      .email.col-12.col-md-4.col-lg-12.row.no-gutters.justify-content-center.mb-5
        .row.no-gutters.col-12.justify-content-center
          %h4.text-tertiary.mx-2 Escribinos
        .row.no-gutters
          %p.text-tertiary info@mundogaia.com

= render 'shared/bottom_background.html.haml'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gaia
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: (params['controller'] == 'welcome' ? ' ' : 'bg-primary-light')}
    = render 'shared/header.html.haml'

    = yield

    = render 'shared/footer.html.haml'

app/views/products/_product.html.haml
= link_to  product_path(product), class: 'product col-10 col-sm-5 col-lg-3 my-3 mx-2 row no-gutters justify-content-center align-items-center' do
  = image_tag product.pictures[0].url, alt: product.name

app/views/products/index.html.haml
= render 'shared/top_background.html.haml', title: t('store')

.full-height-wrapper.d-flex.flex-column.justify-content-center
  .products.row.no-gutters.justify-content-around
    - @products.each do |product|
      = render product

= render 'shared/bottom_background.html.haml'

app/views/products/show.html.haml
= render 'shared/top_background.html.haml', title: @product.name

.full-height-wrapper.d-flex.flex-column.justify-content-center
  .product-details.row.no-gutters.justify-content-center
    %p.description.text-tertiary.px-3.d-none.d-lg-block.col-lg-7
      = @product.description

    = image_tag @product.pictures[0].url, class: 'product-image col-12 col-lg-5', alt: @product.name

    %h3.price.text-tertiary.text-center.col-12.col-lg-7
      = "#{t('activerecord.attributes.product.price')}: #{@product.price}"

    .row.no-gutters.justify-content-center.col-12.col-lg-5
      %button.add-to-cart.btn.btn-secondary.btn-lg.rounded.mb-3
        Añadir al carrito

= render 'shared/bottom_background.html.haml'

app/views/purpose/index.html.haml
= render 'shared/top_background.html.haml', title: t('our_purpose')

.full-height-wrapper.d-flex.flex-column.justify-content-center
  %main#our-purpose
    %p La esencia de Gaia se define de acuerdo con su propósito. El proyecto surge al notar como, en un mundo globalizado, los niños uruguayos suelen conocer animales de todo el mundo, pero no están involucrados con la fauna local.

    %p
      Los animales de la región no suelen ser publicitados como lo son el león, zebra o el oso panda.

    %p
      Ante esto, Gaia busca transmitir y promover el valor de la fauna y flora de cada región de una manera educativa y divertida.

    %p
      Nos definimos como un mundo ya que buscamos estar presentes en todos los círculos de interés del niño - sus rutinas de juego, su familia y su entorno educativo –.

= render 'shared/bottom_background.html.haml'

app/views/shared/_bottom_background.html.haml
#bottom-background
  = image_pack_tag 'bottom_background.png'

app/views/shared/_footer.html.haml
%footer#gaia-footer.row.no-gutters.justify-content-between.align-items-center.py-3.px-4
  %h5.copyright.text-secondary.m-0
    &copy; 2020 Mundo Gaia
  .social-links
    = image_pack_tag 'social_links/facebook_logo.png'
    = image_pack_tag 'social_links/instagram_logo.png'
    = image_pack_tag 'social_links/linkedin_logo.png'
    = image_pack_tag 'social_links/twitter_logo.png'

app/views/shared/_header.html.haml
= javascript_pack_tag 'header'

%header#gaia-header.row.no-gutters.justify-content-between.align-items-center.py-2.px-4
  .cart.d-inline-block.d-lg-none.position-relative
    = image_pack_tag 'cart_icon.svg'
    .counter
      0
  = link_to root_path, class: 'logo h1 m-0' do
    %span.text-tertiary G
    %span.text-primary A
    %span.text-cuaternary I
    %span.text-quinary A
  .header-links.d-none.d-lg-block
    = link_to t('our_purpose'), our_purpose_path
    = link_to t('store'), products_path
    = link_to t('contact_us'), contact_us_path
    = link_to t('blog'), '#'
    .cart.d-inline-block.position-relative
      = image_pack_tag 'cart_icon.svg'
      .counter
        0
  %button.hamburger.hamburger--squeeze.px-0.d-lg-none{type: 'button'}
    %span.hamburger-box
      %span.hamburger-inner
#hamburger-menu.position-absolute.d-none.flex-column.align-items-center.pt-5
  = link_to t('our_purpose'), our_purpose_path, class: 'h4'
  = link_to t('store'), products_path, class: 'h4'
  = link_to t('contact_us'), contact_us_path, class: 'h4'
  = link_to t('blog'), '#', class: 'h4'

app/views/shared/_top_background.html.haml
#top-background.position-relative
  = image_pack_tag 'top_background.png'
  %h4.screen-title.text-secondary.w-25
    = title

app/views/welcome/index.html.haml
= javascript_pack_tag 'map'

#map-container.row.no-gutters.justify-content-center.align-items-center
  #map.py-5
    = image_pack_tag 'south_america.png', id: 'map-image' 
    = image_pack_tag 'animals/carpincho_peluche.png', id: 'carpincho', class: 'animal', title: 'Carpincho', tabindex: '-1', data: { toggle: 'popover', content: "<a class='btn btn-secondary rounded' href='#{product_path(@carpincho)}'>Comprar</a>" }
    = image_pack_tag 'animals/coati_peluche.png', id: 'coati', class: 'animal', title: 'Coati', tabindex: '-1', data: { toggle: 'popover', content: "<a class='btn btn-secondary rounded' href='#{product_path(@coati)}'>Comprar</a>" }
    = image_pack_tag 'animals/tamandua_peluche.png', id: 'tamandua', class: 'animal', title: 'Tamandua', tabindex: '-1', data: { toggle: 'popover', content: "<a class='btn btn-secondary rounded' href='#{product_path(@tamandua)}'>Comprar</a>" }